/* Common FPS v0.28b SR9K - direct System.Action ctor(native ptr) queue proof; no UI mutation */
#include <netinet/in.h>
#include <ps5/kernel.h>
#include <stdint.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

#define LOOPBACK_ADDRESS 0x0100007fu
#define RESULT_PORT_NETWORK 0xFED8u /* htons(55550) */
#define RESULT_MAGIC 0x4b39444eu /* ND9K */
#define KIND_STAGE 1u
#define KIND_RESULT 2u
#define KIND_DONE 3u
#define KIND_ERROR 4u

typedef void MonoDomain; typedef void MonoThread; typedef void MonoAssembly; typedef void MonoImage; typedef void MonoClass; typedef void MonoMethod; typedef void MonoString; typedef void MonoObject; typedef void MonoProperty;
typedef MonoDomain*(*mono_get_root_domain_fn)(void); typedef MonoThread*(*mono_thread_attach_fn)(MonoDomain*); typedef MonoAssembly*(*mono_domain_assembly_open_fn)(MonoDomain*,const char*); typedef MonoImage*(*mono_assembly_get_image_fn)(MonoAssembly*); typedef MonoImage*(*mono_get_corlib_fn)(void); typedef MonoClass*(*mono_class_from_name_fn)(MonoImage*,const char*,const char*); typedef MonoMethod*(*mono_class_get_method_from_name_fn)(MonoClass*,const char*,int); typedef MonoString*(*mono_string_new_fn)(MonoDomain*,const char*); typedef MonoDomain*(*mono_domain_get_fn)(void); typedef MonoObject*(*mono_runtime_invoke_fn)(MonoMethod*,void*,void**,MonoObject**); typedef MonoProperty*(*mono_class_get_property_from_name_fn)(MonoClass*,const char*); typedef MonoMethod*(*mono_property_get_get_method_fn)(MonoProperty*); typedef MonoObject*(*mono_object_new_fn)(MonoDomain*,MonoClass*); typedef MonoClass*(*mono_object_get_class_fn)(MonoObject*); typedef const char*(*mono_class_get_name_fn)(MonoClass*);

struct pkt{uint32_t magic,kind;uint64_t seq;int32_t value;uint32_t code;char detail[96];char extra[160];};
static int s=-1; static struct sockaddr_in dst; static uint64_t seq=1; static volatile uint32_t native_seen=0;
static mono_get_root_domain_fn mono_get_root_domain_; static mono_thread_attach_fn mono_thread_attach_; static mono_domain_assembly_open_fn mono_domain_assembly_open_; static mono_assembly_get_image_fn mono_assembly_get_image_; static mono_get_corlib_fn mono_get_corlib_; static mono_class_from_name_fn mono_class_from_name_; static mono_class_get_method_from_name_fn mono_class_get_method_from_name_; static mono_string_new_fn mono_string_new_; static mono_domain_get_fn mono_domain_get_; static mono_runtime_invoke_fn mono_runtime_invoke_; static mono_class_get_property_from_name_fn mono_class_get_property_from_name_; static mono_property_get_get_method_fn mono_property_get_get_method_; static mono_object_new_fn mono_object_new_; static mono_object_get_class_fn mono_object_get_class_; static mono_class_get_name_fn mono_class_get_name_;
#define R(h,n,t) do{n##_=(t)(uintptr_t)kernel_dynlib_dlsym(getpid(),h,#n);}while(0)
static void native_queue_callback(void){__atomic_store_n((uint32_t*)&native_seen,1u,__ATOMIC_RELEASE);}
static void sendp(uint32_t kind,uint32_t code,int32_t value,const char*d,const char*e){struct pkt p;memset(&p,0,sizeof(p));p.magic=RESULT_MAGIC;p.kind=kind;p.seq=seq++;p.code=code;p.value=value;if(d)strncpy(p.detail,d,sizeof(p.detail)-1);if(e)strncpy(p.extra,e,sizeof(p.extra)-1);(void)sendto(s,&p,sizeof(p),0,(const struct sockaddr*)&dst,sizeof(dst));}
static int fail(uint32_t c,const char*d,const char*e){sendp(KIND_ERROR,c,-1,d,e);if(s>=0)close(s);return (int)c;}

int main(void){
 s=socket(AF_INET,SOCK_DGRAM,0);if(s<0)return 10;memset(&dst,0,sizeof(dst));dst.sin_family=AF_INET;dst.sin_port=RESULT_PORT_NETWORK;dst.sin_addr.s_addr=LOOPBACK_ADDRESS;sendp(KIND_STAGE,0,0,"SR9K","START_DIRECT_ACTION_CTOR_PROOF");
 uint32_t h=0;if(kernel_dynlib_handle(getpid(),"libmonosgen-2.0.sprx",&h)!=0||!h){h=0;if(kernel_dynlib_handle(getpid(),"libmonosgen-2.0.0.sprx",&h)!=0||!h)return fail(21,"Mono","MODULE_NOT_FOUND");}
 R(h,mono_get_root_domain,mono_get_root_domain_fn);R(h,mono_thread_attach,mono_thread_attach_fn);R(h,mono_domain_assembly_open,mono_domain_assembly_open_fn);R(h,mono_assembly_get_image,mono_assembly_get_image_fn);R(h,mono_get_corlib,mono_get_corlib_fn);R(h,mono_class_from_name,mono_class_from_name_fn);R(h,mono_class_get_method_from_name,mono_class_get_method_from_name_fn);R(h,mono_string_new,mono_string_new_fn);R(h,mono_domain_get,mono_domain_get_fn);R(h,mono_runtime_invoke,mono_runtime_invoke_fn);R(h,mono_class_get_property_from_name,mono_class_get_property_from_name_fn);R(h,mono_property_get_get_method,mono_property_get_get_method_fn);R(h,mono_object_new,mono_object_new_fn);R(h,mono_object_get_class,mono_object_get_class_fn);R(h,mono_class_get_name,mono_class_get_name_fn);
 if(!mono_get_root_domain_||!mono_thread_attach_||!mono_domain_assembly_open_||!mono_assembly_get_image_||!mono_get_corlib_||!mono_class_from_name_||!mono_class_get_method_from_name_||!mono_string_new_||!mono_domain_get_||!mono_runtime_invoke_||!mono_class_get_property_from_name_||!mono_property_get_get_method_||!mono_object_new_||!mono_object_get_class_||!mono_class_get_name_)return fail(22,"Mono","SYMBOL_MISSING");
 MonoDomain*root=mono_get_root_domain_();if(!root||!mono_thread_attach_(root))return fail(23,"Mono","THREAD_ATTACH_FAILED");sendp(KIND_STAGE,0,0,"Mono","THREAD_ATTACHED");
 MonoAssembly*pa=mono_domain_assembly_open_(root,"/system_ex/common_ex/lib/Sce.PlayStation.PUI.dll");MonoImage*pui=pa?mono_assembly_get_image_(pa):0;MonoAssembly*aa=mono_domain_assembly_open_(root,"/system_ex/common_ex/lib/Sce.Vsh.ShellUI.AppSystem.dll");MonoImage*appimg=aa?mono_assembly_get_image_(aa):0;MonoImage*cor=mono_get_corlib_();if(!pui||!appimg||!cor)return fail(24,"Assemblies","IMAGE_NOT_READY");
 MonoClass*appc=mono_class_from_name_(pui,"Sce.PlayStation.PUI","Application");MonoMethod*geti=appc?mono_class_get_method_from_name_(appc,"get_Instance",0):0;MonoMethod*enqueue=appc?mono_class_get_method_from_name_(appc,"EnqueueEventAction",2):0;if(!geti||!enqueue)return fail(25,"Application","METHOD_NOT_FOUND");MonoObject*exc=0;MonoObject*app=mono_runtime_invoke_(geti,0,0,&exc);if(!app||exc)return fail(26,"Application","INSTANCE_FAILED");
 MonoClass*layer=mono_class_from_name_(appimg,"Sce.Vsh.ShellUI.AppSystem","LayerManager");MonoMethod*find=layer?mono_class_get_method_from_name_(layer,"FindContainerSceneByPath",1):0;if(!find)return fail(27,"LayerManager","FIND_SCENE_MISSING");MonoDomain*cur=mono_domain_get_();if(!cur)cur=root;MonoString*gs=mono_string_new_(cur,"Game");void*sa[1]={gs};exc=0;MonoObject*game=mono_runtime_invoke_(find,0,sa,&exc);if(!game||exc)return fail(28,"LayerManager","GAME_SCENE_FAILED");
 MonoClass*scene=mono_class_from_name_(pui,"Sce.PlayStation.PUI.UI2","Scene");MonoProperty*rp=scene?mono_class_get_property_from_name_(scene,"RootWidget"):0;MonoMethod*rg=rp?mono_property_get_get_method_(rp):0;exc=0;MonoObject*rw=rg?mono_runtime_invoke_(rg,game,0,&exc):0;if(!rw||exc)return fail(29,"Scene","ROOT_WIDGET_FAILED");sendp(KIND_STAGE,0,0,"PUI","ROOT_WIDGET_READY");
 MonoClass*actionc=mono_class_from_name_(cor,"System","Action");MonoMethod*actor=actionc?mono_class_get_method_from_name_(actionc,".ctor",2):0;if(!actionc||!actor)return fail(30,"System.Action","CTOR_NOT_FOUND");MonoObject*action=mono_object_new_(root,actionc);if(!action)return fail(31,"System.Action","ALLOC_FAILED");void*nptr=(void*)(uintptr_t)&native_queue_callback;void*ca[2]={0,&nptr};exc=0;(void)mono_runtime_invoke_(actor,action,ca,&exc);if(exc)return fail(32,"System.Action","DIRECT_CTOR_EXCEPTION");MonoClass*actual=mono_object_get_class_(action);const char*name=actual?mono_class_get_name_(actual):0;if(!name||strcmp(name,"Action")!=0)return fail(33,"System.Action","TYPE_VERIFY_FAILED");sendp(KIND_STAGE,0,0,"System.Action","DIRECT_ACTION_CTOR_READY");
 __atomic_store_n((uint32_t*)&native_seen,0u,__ATOMIC_RELEASE);void*ea[2]={rw,action};exc=0;(void)mono_runtime_invoke_(enqueue,app,ea,&exc);if(exc)return fail(34,"EnqueueEventAction","INVOKE_EXCEPTION");sendp(KIND_STAGE,0,0,"EnqueueEventAction","DIRECT_NATIVE_ACTION_SUBMITTED");uint32_t seen=0;for(unsigned i=0;i<200;++i){usleep(10000);seen=__atomic_load_n((uint32_t*)&native_seen,__ATOMIC_ACQUIRE);if(seen==1u)break;}sendp(KIND_RESULT,0,(int32_t)seen,"NATIVE_CALLBACK_SEEN",seen==1u?"ACTION_EXECUTED":"ACTION_NOT_OBSERVED");if(seen!=1u)return fail(35,"NativeAction","CALLBACK_TIMEOUT");sendp(KIND_DONE,0,1,"SR9K","PASS_DIRECT_ACTION_CTOR_NATIVE_QUEUE");close(s);return 0;
}
