/* Common FPS v0.28b SR9L - queued Label.Text setter through proven native UI callback; no tree mutation */
#include <netinet/in.h>
#include <ps5/kernel.h>
#include <stdint.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

#define LOOPBACK_ADDRESS 0x0100007fu
#define RESULT_PORT_NETWORK 0xFFD8u /* htons(55551) */
#define RESULT_MAGIC 0x4c395453u /* ST9L */
#define KIND_STAGE 1u
#define KIND_RESULT 2u
#define KIND_DONE 3u
#define KIND_ERROR 4u

typedef void MonoDomain; typedef void MonoThread; typedef void MonoAssembly; typedef void MonoImage; typedef void MonoClass; typedef void MonoMethod; typedef void MonoString; typedef void MonoObject; typedef void MonoProperty;
typedef MonoDomain*(*mono_get_root_domain_fn)(void); typedef MonoThread*(*mono_thread_attach_fn)(MonoDomain*); typedef MonoAssembly*(*mono_domain_assembly_open_fn)(MonoDomain*,const char*); typedef MonoImage*(*mono_assembly_get_image_fn)(MonoAssembly*); typedef MonoImage*(*mono_get_corlib_fn)(void); typedef MonoClass*(*mono_class_from_name_fn)(MonoImage*,const char*,const char*); typedef MonoMethod*(*mono_class_get_method_from_name_fn)(MonoClass*,const char*,int); typedef MonoString*(*mono_string_new_fn)(MonoDomain*,const char*); typedef char*(*mono_string_to_utf8_fn)(MonoString*); typedef MonoDomain*(*mono_domain_get_fn)(void); typedef MonoObject*(*mono_runtime_invoke_fn)(MonoMethod*,void*,void**,MonoObject**); typedef MonoProperty*(*mono_class_get_property_from_name_fn)(MonoClass*,const char*); typedef MonoMethod*(*mono_property_get_get_method_fn)(MonoProperty*); typedef MonoMethod*(*mono_property_get_set_method_fn)(MonoProperty*); typedef MonoObject*(*mono_object_new_fn)(MonoDomain*,MonoClass*); typedef void*(*mono_compile_method_fn)(MonoMethod*); typedef void*(*mono_object_unbox_fn)(MonoObject*);

struct pkt{uint32_t magic,kind;uint64_t seq;int32_t value;uint32_t code;char detail[96];char extra[160];};
static int s=-1; static struct sockaddr_in dst; static uint64_t seq=1;
static mono_get_root_domain_fn mono_get_root_domain_; static mono_thread_attach_fn mono_thread_attach_; static mono_domain_assembly_open_fn mono_domain_assembly_open_; static mono_assembly_get_image_fn mono_assembly_get_image_; static mono_get_corlib_fn mono_get_corlib_; static mono_class_from_name_fn mono_class_from_name_; static mono_class_get_method_from_name_fn mono_class_get_method_from_name_; static mono_string_new_fn mono_string_new_; static mono_string_to_utf8_fn mono_string_to_utf8_; static mono_domain_get_fn mono_domain_get_; static mono_runtime_invoke_fn mono_runtime_invoke_; static mono_class_get_property_from_name_fn mono_class_get_property_from_name_; static mono_property_get_get_method_fn mono_property_get_get_method_; static mono_property_get_set_method_fn mono_property_get_set_method_; static mono_object_new_fn mono_object_new_; static mono_compile_method_fn mono_compile_method_; static mono_object_unbox_fn mono_object_unbox_;
#define R(h,n,t) do{n##_=(t)(uintptr_t)kernel_dynlib_dlsym(getpid(),h,#n);}while(0)

static MonoObject* g_label=0; static MonoString* g_text=0; static MonoMethod* g_text_setter=0; static volatile uint32_t g_text_status=0;
static void native_text_callback(void){
 if(!g_label||!g_text||!g_text_setter||!mono_runtime_invoke_){__atomic_store_n((uint32_t*)&g_text_status,2u,__ATOMIC_RELEASE);return;}
 void*args[1]={g_text}; MonoObject*exc=0; (void)mono_runtime_invoke_(g_text_setter,g_label,args,&exc);
 __atomic_store_n((uint32_t*)&g_text_status,exc?2u:1u,__ATOMIC_RELEASE);
}

static void sendp(uint32_t kind,uint32_t code,int32_t value,const char*d,const char*e){struct pkt p;memset(&p,0,sizeof(p));p.magic=RESULT_MAGIC;p.kind=kind;p.seq=seq++;p.code=code;p.value=value;if(d)strncpy(p.detail,d,sizeof(p.detail)-1);if(e)strncpy(p.extra,e,sizeof(p.extra)-1);(void)sendto(s,&p,sizeof(p),0,(const struct sockaddr*)&dst,sizeof(dst));}
static int fail(uint32_t c,const char*d,const char*e){sendp(KIND_ERROR,c,-1,d,e);if(s>=0)close(s);return (int)c;}
static int32_t get_count(MonoMethod*m,MonoObject*o,int*ok){MonoObject*x=0,*b=mono_runtime_invoke_(m,o,0,&x);if(x||!b){*ok=0;return -1;}void*r=mono_object_unbox_(b);if(!r){*ok=0;return -1;}*ok=1;return *(int32_t*)r;}
static MonoObject* make_action(MonoDomain*root,MonoClass*action_class,MonoMethod*ctor,MonoObject*target_obj,MonoMethod*target_method){MonoObject*a=mono_object_new_(root,action_class);if(!a)return 0;void*fp=mono_compile_method_(target_method);if(!fp)return 0;void*args[2]={target_obj,&fp};MonoObject*exc=0;(void)mono_runtime_invoke_(ctor,a,args,&exc);return exc?0:a;}
static MonoObject* make_native_action(MonoDomain*root,MonoClass*action_class,MonoMethod*ctor){MonoObject*a=mono_object_new_(root,action_class);if(!a)return 0;void*fp=(void*)(uintptr_t)&native_text_callback;void*args[2]={0,&fp};MonoObject*exc=0;(void)mono_runtime_invoke_(ctor,a,args,&exc);return exc?0:a;}

int main(void){
 s=socket(AF_INET,SOCK_DGRAM,0);if(s<0)return 10;memset(&dst,0,sizeof(dst));dst.sin_family=AF_INET;dst.sin_port=RESULT_PORT_NETWORK;dst.sin_addr.s_addr=LOOPBACK_ADDRESS;sendp(KIND_STAGE,0,0,"SR9L","START_LABEL_TEXT_QUEUE_PROOF");
 uint32_t h=0;if(kernel_dynlib_handle(getpid(),"libmonosgen-2.0.sprx",&h)!=0||!h){h=0;if(kernel_dynlib_handle(getpid(),"libmonosgen-2.0.0.sprx",&h)!=0||!h)return fail(21,"Mono","MODULE_NOT_FOUND");}
 R(h,mono_get_root_domain,mono_get_root_domain_fn);R(h,mono_thread_attach,mono_thread_attach_fn);R(h,mono_domain_assembly_open,mono_domain_assembly_open_fn);R(h,mono_assembly_get_image,mono_assembly_get_image_fn);R(h,mono_get_corlib,mono_get_corlib_fn);R(h,mono_class_from_name,mono_class_from_name_fn);R(h,mono_class_get_method_from_name,mono_class_get_method_from_name_fn);R(h,mono_string_new,mono_string_new_fn);R(h,mono_string_to_utf8,mono_string_to_utf8_fn);R(h,mono_domain_get,mono_domain_get_fn);R(h,mono_runtime_invoke,mono_runtime_invoke_fn);R(h,mono_class_get_property_from_name,mono_class_get_property_from_name_fn);R(h,mono_property_get_get_method,mono_property_get_get_method_fn);R(h,mono_property_get_set_method,mono_property_get_set_method_fn);R(h,mono_object_new,mono_object_new_fn);R(h,mono_compile_method,mono_compile_method_fn);R(h,mono_object_unbox,mono_object_unbox_fn);
 if(!mono_get_root_domain_||!mono_thread_attach_||!mono_domain_assembly_open_||!mono_assembly_get_image_||!mono_get_corlib_||!mono_class_from_name_||!mono_class_get_method_from_name_||!mono_string_new_||!mono_string_to_utf8_||!mono_domain_get_||!mono_runtime_invoke_||!mono_class_get_property_from_name_||!mono_property_get_get_method_||!mono_property_get_set_method_||!mono_object_new_||!mono_compile_method_||!mono_object_unbox_)return fail(22,"Mono","SYMBOL_MISSING");
 MonoDomain*root=mono_get_root_domain_();if(!root||!mono_thread_attach_(root))return fail(23,"Mono","THREAD_ATTACH_FAILED");sendp(KIND_STAGE,0,0,"Mono","THREAD_ATTACHED");
 MonoAssembly*pa=mono_domain_assembly_open_(root,"/system_ex/common_ex/lib/Sce.PlayStation.PUI.dll");MonoImage*pui=pa?mono_assembly_get_image_(pa):0;MonoAssembly*aa=mono_domain_assembly_open_(root,"/system_ex/common_ex/lib/Sce.Vsh.ShellUI.AppSystem.dll");MonoImage*appimg=aa?mono_assembly_get_image_(aa):0;MonoImage*cor=mono_get_corlib_();if(!pui||!appimg||!cor)return fail(24,"Assemblies","IMAGE_NOT_READY");
 MonoClass*appc=mono_class_from_name_(pui,"Sce.PlayStation.PUI","Application");MonoMethod*geti=appc?mono_class_get_method_from_name_(appc,"get_Instance",0):0;MonoMethod*enqueue=appc?mono_class_get_method_from_name_(appc,"EnqueueEventAction",2):0;if(!geti||!enqueue)return fail(25,"Application","METHOD_NOT_FOUND");MonoObject*exc=0;MonoObject*app=mono_runtime_invoke_(geti,0,0,&exc);if(!app||exc)return fail(26,"Application","INSTANCE_FAILED");
 MonoClass*layer=mono_class_from_name_(appimg,"Sce.Vsh.ShellUI.AppSystem","LayerManager");MonoMethod*find=layer?mono_class_get_method_from_name_(layer,"FindContainerSceneByPath",1):0;if(!find)return fail(27,"LayerManager","FIND_SCENE_MISSING");MonoDomain*cur=mono_domain_get_();if(!cur)cur=root;MonoString*gs=mono_string_new_(cur,"Game");void*sa[1]={gs};exc=0;MonoObject*game=mono_runtime_invoke_(find,0,sa,&exc);if(!game||exc)return fail(28,"LayerManager","GAME_SCENE_FAILED");
 MonoClass*scene=mono_class_from_name_(pui,"Sce.PlayStation.PUI.UI2","Scene");MonoProperty*rp=scene?mono_class_get_property_from_name_(scene,"RootWidget"):0;MonoMethod*rg=rp?mono_property_get_get_method_(rp):0;exc=0;MonoObject*rw=rg?mono_runtime_invoke_(rg,game,0,&exc):0;if(!rw||exc)return fail(29,"Scene","ROOT_WIDGET_FAILED");sendp(KIND_STAGE,0,0,"PUI","ROOT_WIDGET_READY");
 MonoClass*labelc=mono_class_from_name_(pui,"Sce.PlayStation.PUI.UI2","Label");MonoMethod*labelctor=labelc?mono_class_get_method_from_name_(labelc,".ctor",0):0;MonoProperty*textp=labelc?mono_class_get_property_from_name_(labelc,"Text"):0;MonoMethod*textset=textp?mono_property_get_set_method_(textp):0;MonoMethod*textget=textp?mono_property_get_get_method_(textp):0;if(!labelc||!labelctor||!textset||!textget)return fail(30,"Label.Text","METHOD_NOT_FOUND");MonoObject*label=mono_object_new_(root,labelc);if(!label)return fail(31,"Label","ALLOC_FAILED");MonoString*text=mono_string_new_(root,"FPS TEST");if(!text)return fail(32,"Label.Text","STRING_FAILED");g_label=label;g_text=text;g_text_setter=textset;sendp(KIND_STAGE,0,0,"Label.Text","OBJECT_AND_VALUE_READY_OFF_TREE");
 MonoClass*listc=mono_class_from_name_(cor,"System.Collections","ArrayList");MonoMethod*lctor=listc?mono_class_get_method_from_name_(listc,".ctor",0):0;MonoMethod*ladd=listc?mono_class_get_method_from_name_(listc,"Add",1):0;MonoMethod*lclear=listc?mono_class_get_method_from_name_(listc,"Clear",0):0;MonoMethod*lcount=listc?mono_class_get_method_from_name_(listc,"get_Count",0):0;if(!lctor||!ladd||!lclear||!lcount)return fail(33,"ArrayList","METHOD_NOT_FOUND");MonoObject*list=mono_object_new_(root,listc);if(!list)return fail(34,"ArrayList","NEW_FAILED");exc=0;(void)mono_runtime_invoke_(lctor,list,0,&exc);if(exc)return fail(35,"ArrayList","CTOR_EXCEPTION");void*adda[1]={app};exc=0;(void)mono_runtime_invoke_(ladd,list,adda,&exc);if(exc)return fail(36,"ArrayList","ADD_EXCEPTION");int ok=0;int32_t before=get_count(lcount,list,&ok);if(!ok||before!=1)return fail(37,"ArrayList","COUNT_BEFORE_BAD");sendp(KIND_RESULT,0,before,"COUNT_BEFORE","EXPECTED_1");
 MonoClass*actionc=mono_class_from_name_(cor,"System","Action");MonoMethod*actor=actionc?mono_class_get_method_from_name_(actionc,".ctor",2):0;MonoClass*delc=mono_class_from_name_(cor,"System","Delegate");MonoMethod*combine=delc?mono_class_get_method_from_name_(delc,"Combine",2):0;if(!actor||!combine)return fail(38,"Delegate","METHOD_NOT_FOUND");MonoObject*a_ctor=make_action(root,actionc,actor,label,labelctor);MonoObject*a_text=make_native_action(root,actionc,actor);MonoObject*a_clear=make_action(root,actionc,actor,list,lclear);if(!a_ctor||!a_text||!a_clear)return fail(39,"System.Action","BUILD_FAILED");void*c1args[2]={a_ctor,a_text};exc=0;MonoObject*c1=mono_runtime_invoke_(combine,0,c1args,&exc);if(!c1||exc)return fail(40,"Delegate","COMBINE_1_FAILED");void*c2args[2]={c1,a_clear};exc=0;MonoObject*multi=mono_runtime_invoke_(combine,0,c2args,&exc);if(!multi||exc)return fail(41,"Delegate","COMBINE_2_FAILED");sendp(KIND_STAGE,0,0,"System.Action","CTOR_TEXT_CLEAR_CHAIN_READY");
 __atomic_store_n((uint32_t*)&g_text_status,0u,__ATOMIC_RELEASE);void*ea[2]={rw,multi};exc=0;(void)mono_runtime_invoke_(enqueue,app,ea,&exc);if(exc)return fail(42,"EnqueueEventAction","INVOKE_EXCEPTION");sendp(KIND_STAGE,0,0,"EnqueueEventAction","SUBMITTED");int32_t after=before;for(unsigned i=0;i<200;++i){usleep(10000);ok=0;after=get_count(lcount,list,&ok);if(!ok)return fail(43,"ArrayList","COUNT_READ_FAILED");if(after==0)break;}uint32_t status=__atomic_load_n((uint32_t*)&g_text_status,__ATOMIC_ACQUIRE);sendp(KIND_RESULT,0,(int32_t)status,"TEXT_SETTER_STATUS",status==1u?"SETTER_RETURNED_OK":"SETTER_FAILED_OR_NOT_SEEN");if(after!=0)return fail(44,"EnqueueEventAction","ACTION_TIMEOUT");if(status!=1u)return fail(45,"Label.Text","SETTER_CALLBACK_FAILED");
 exc=0;MonoObject*got=mono_runtime_invoke_(textget,label,0,&exc);if(!got||exc)return fail(46,"Label.Text","GETTER_FAILED");char*utf8=mono_string_to_utf8_((MonoString*)got);if(!utf8||strcmp(utf8,"FPS TEST")!=0)return fail(47,"Label.Text","VERIFY_MISMATCH");sendp(KIND_RESULT,0,1,"TEXT_VERIFY","FPS TEST");sendp(KIND_RESULT,0,after,"COUNT_AFTER","CTOR_TEXT_ACTION_CHAIN_EXECUTED");sendp(KIND_DONE,0,1,"SR9L","PASS_LABEL_TEXT_THROUGH_NATIVE_UI_CALLBACK");close(s);return 0;
}
