#!/usr/bin/env python3
"""Convert a binary file into a C++ byte array for source-built embedding."""

from __future__ import annotations

import argparse
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    data = args.input.read_bytes()
    if len(data) < 4 or data[:4] != b"\x7fELF":
        raise SystemExit(f"input is not an ELF: {args.input}")

    args.output.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "/* Generated by tools/embed_binary_cpp.py. Do not edit. */",
        '#include "embedded_renderer.hpp"',
        "",
        "namespace common_fps::ps5::embedded_renderer {",
        "",
        "alignas(16) const unsigned char kData[] = {",
    ]

    width = 16
    for i in range(0, len(data), width):
        chunk = data[i : i + width]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

    lines.extend(
        [
            "};",
            "",
            "const std::size_t kSize = sizeof(kData);",
            "",
            "} // namespace common_fps::ps5::embedded_renderer",
            "",
        ]
    )

    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"embedded {len(data)} bytes from {args.input} -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
