#!/usr/bin/env python3
"""Generate a C++ translation unit that embeds one binary file.

Usage:
  embed_binary.py INPUT OUTPUT

The generated symbols match src/ps5/embedded_shellui.hpp.
"""

from __future__ import annotations

import pathlib
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: embed_binary.py INPUT OUTPUT", file=sys.stderr)
        return 2

    src = pathlib.Path(sys.argv[1])
    dst = pathlib.Path(sys.argv[2])
    data = src.read_bytes()

    dst.parent.mkdir(parents=True, exist_ok=True)

    with dst.open("w", encoding="utf-8", newline="\n") as out:
        out.write("// Generated by tools/embed_binary.py. Do not edit.\n")
        out.write('#include "embedded_shellui.hpp"\n\n')
        out.write("namespace common_fps::ps5::embedded {\n\n")
        out.write("alignas(16) const unsigned char kShellUIElf[] = {\n")

        for offset in range(0, len(data), 16):
            chunk = data[offset : offset + 16]
            out.write("    ")
            out.write(", ".join(f"0x{byte:02x}" for byte in chunk))
            out.write(",\n")

        out.write("};\n\n")
        out.write("const std::size_t kShellUIElfSize = sizeof(kShellUIElf);\n\n")
        out.write("} // namespace common_fps::ps5::embedded\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
